import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'

const comfortaa = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pommy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={comfortaa.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
